### ISSUE TITLE
Darmstadtium needs your help!

### ISSUE THREAD

**Issue by jsbeckr** [ablakey/periodic#3]
Hi there!

Saw you on HackerNews congrats! 👍 

Darmstadt, Germany has its own element and would like to be part of your site 😏 

Have a nice weekend!

**Comment by ablakey** [comment]
Hi Jens! If your repo exists and shares the same name as the element, it will automatically be added the next time I run the script (later this weekend) *if* it is the highest starred repo with that name.  If you don't see it by the end of the weekend, let me know.

Thanks!
